- name: Deploy CrateDB
  hosts: crate-nodes
  become: yes
  tasks:
  - name: Update apt cache
    apt:
      update_cache: yes
  - name: Install dependencies
    apt: name={{item}} state=latest
    with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python-pip
  - name: Install Python dependencies
    pip: name={{item}}
    with_items:
      - docker-py
  - name: Add Docker repository key
    apt_key:
      id: "58118E89F3A912897C070ADBF76221572C52609D"
      keyserver: "hkp://p80.pool.sks-keyservers.net:80"
      state: present
    register: add_repository_key
    ignore_errors: true
  - name: Add Docker repository and update apt cache
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/debian jessie stable"
      mode: '644'
      update_cache: yes
      state: present
  - name: Install Docker CE
    apt: name=docker-ce state=latest allow_unauthenticated=yes
  - name: Start Docker
    service:
      name: docker
      state: started
  - name: Create CrateDB data folder
    file:
      path: /opt/crate/data
      state: directory
      mode: 0755
  - name: Create Traefik config folder
    file:
      path: /opt/traefik
      state: directory
      mode: 0755
  - name: Traefik config
    template:
      src: traefik.toml.j2
      dest: /opt/traefik/traefik.toml
  - name: Start CrateDB container
    docker_container:
      name: cratedb
      image: crate/crate:1.1.2
      pull: true
      recreate: yes
      restart_policy: unless-stopped
      ulimits:
        - "nofile:65535"
        - "memlock:9223372036854775807"
      env:
        CRATE_HEAP_SIZE: "{{ ((ram // 2) > 31) | ternary(32, ram // 2) }}g"
      command: "crate -Cgateway.expected_nodes={{ groups['crate-nodes'] | length }} -Cgateway.recover_after_nodes={{ (groups['crate-nodes'] | length) // 2 + 1 }} -Cdiscovery.zen.minimum_master_nodes={{ (groups['crate-nodes'] | length) // 2 + 1 }} -Cdiscovery.zen.ping.multicast.enabled=false -Chttp.cors.enabled=true -Chttp.cors.allow-origin='*' -Cdiscovery.zen.ping.unicast.hosts={{groups['crate-nodes']|map('extract', hostvars, 'private_ip')|list| join(',') }} -Cnetwork.publish_host={{private_ip}} -Ccluster.name=Sensordata@CrateDB -Cindices.store.throttle.type=none -Clicense.enterprise=true"
      state: started
      published_ports:
      - "{{private_ip}}:4200:4200" # HTTP port
      - "{{private_ip}}:4300:4300" # Internal communication
      - "{{private_ip}}:5432:5432" # PSQL port
      volumes:
      - /opt/crate/data:/data
  - name: Start traefik loadbalancer
    docker_container:
      name: traefik
      image: traefik:latest
      pull: yes
      recreate: yes
      restart_policy: unless-stopped
      command: "traefik"
      state: started
      published_ports:
      - "{{ansible_host}}:4280:4280" #
      volumes:
      - /opt/traefik/traefik.toml:/etc/traefik/traefik.toml
